---
title: "Analysis_Pseudo-pair"
author: "Xiaochun Han"
date: "2025-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix"))
```

## Import data
```{r impart data}
setwd('./permute407_WINS_BINS_FC_BOLD_all')
wd<-getwd()
dataset_BINS <- read.csv('permute_BNC_single_trial.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('permute_WNC_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- read.csv('win_lose_pseudo_permute.csv',header=TRUE,sep=",")

INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE,FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win",FALSE,FALSE)
data_INS_BINS_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)])
```

## Predicting win vs. lose
### INS and BINS
#### 5-fold
```{r svm_invest_INS&BINS-5}
acc_ins_bins = svm_cv_accuracy(data_INS_BINS_invest,5,100,"radial")
print(acc_ins_bins)
```

### auc
```{r svm_invest_INS&BINS}
auc_ins_bins = auc_boot_cv(data_INS_BINS_invest,5,"radial",1000,TRUE,'#5BB9E8','pseudo_data_INS_BINS_invest_roc_plot.png')
```
