---
title: "S01_SVM_outcome_prediction"
author: "Xiaochun Han"
date: "2025-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix"))
```

## Import data
```{r impart data}
setwd('../../Data/Develop')
wd<-getwd()
dataset_BOLD <- read.csv('BOLD_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_FC <- read.csv('FC_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_BINS <- read.csv('BINS_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('INS_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

BOLD_mean = extract_win_or_pay_mean(dataset_BOLD,dataset_y_attack,"BOLD_","win","separate","current",FALSE,FALSE)
FC_mean = extract_win_or_pay_mean(dataset_FC,dataset_y_attack,"FC_","win","separate","current",FALSE,FALSE)
INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win","separate","current",FALSE,FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win","separate","current",FALSE,FALSE)
data_all_outcome = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BINS_mean[,4:ncol(BINS_mean)],BOLD_mean[,4:ncol(BOLD_mean)],FC_mean[,4:ncol(FC_mean)])
data_INS_BINS_outcome = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BINS_mean[,4:ncol(BINS_mean)])
data_BOLD_FC_outcome = cbind(BOLD_mean[,c(1,4:ncol(BOLD_mean))],FC_mean[,4:ncol(FC_mean)])

data_WNS_outcome = INS_mean[,c(1,4:ncol(INS_mean))]
data_BNS_outcome = BINS_mean[,c(1,4:ncol(BINS_mean))]
data_BOLD_outcome = BOLD_mean[,c(1,4:ncol(BOLD_mean))]
data_FC_outcome = FC_mean[,c(1,4:ncol(FC_mean))]

data_minus_WNS_outcome = cbind(BINS_mean[,c(1,4:ncol(BINS_mean))],BOLD_mean[,4:ncol(BOLD_mean)],FC_mean[,4:ncol(FC_mean)])
data_minus_BNS_outcome = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BOLD_mean[,4:ncol(BOLD_mean)],FC_mean[,4:ncol(FC_mean)])
data_minus_BOLD_outcome = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BINS_mean[,4:ncol(BINS_mean)],FC_mean[,4:ncol(FC_mean)])
data_minus_FC_outcome = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BINS_mean[,4:ncol(BINS_mean)],BOLD_mean[,4:ncol(BOLD_mean)])
```

## Predicting win vs. lose
### All features
```{r svm_invest_all}
acc_all = svm_cv_accuracy(data_all_outcome,5,100,"acc_single","radial")
print(acc_all)
```

### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = svm_cv_accuracy(data_BOLD_FC_outcome,5,100,"acc_single","radial")
print(acc_bold_fc)
```

### INS and BINS
```{r svm_invest_INS&BINS}
acc_ins_bins = svm_cv_accuracy(data_INS_BINS_outcome,5,100,"acc_single","radial")
print(acc_ins_bins)
```

### minus WNS
```{r svm_invest_minus_WNS}
acc_minus_wns = svm_cv_accuracy(data_minus_WNS_outcome,5,100,"acc_single","radial")
print(acc_minus_wns)
```

### minus BNS
```{r svm_invest_minus_BNS}
acc_minus_bns = svm_cv_accuracy(data_minus_BNS_outcome,5,100,"acc_single","radial")
print(acc_minus_bns)
```

### minus BOLD
```{r svm_invest_minus_BOLD}
acc_minus_bold = svm_cv_accuracy(data_minus_BOLD_outcome,5,100,"acc_single","radial")
print(acc_minus_bold)
```

### minus FC
```{r svm_invest_minus_FC}
acc_minus_fc = svm_cv_accuracy(data_minus_FC_outcome,5,100,"acc_single","radial")
print(acc_minus_fc)
```

### INS
```{r svm_invest_INS}
acc_wns = svm_cv_accuracy(data_WNS_outcome,5,100,"acc_single","radial")
print(acc_wns)
```

### BNS
```{r svm_invest_BNS}
acc_bns = svm_cv_accuracy(data_BNS_outcome,5,100,"acc_single","radial")
print(acc_bns)
```

### BOLD
```{r svm_invest_BOLD}
acc_bold = svm_cv_accuracy(data_BOLD_outcome,5,100,"acc_single","radial")
print(acc_bold)
```

### FC
```{r svm_invest_FC}
acc_fc = svm_cv_accuracy(data_FC_outcome,5,100,"acc_single","radial")
print(acc_fc)
```
