---
title: "Analysis3A_infoTrack_groupSuccess_correlation"
author: "Xiaochun Han"
date: "2025-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix","plotrix","psych","readxl","ggpubr","car"))
```

## reorg data
```{r reorg data}
tr <- read_excel('DAFD_Behavior_Neural_30sess_behav_cor_LIME_20250522.xlsx',sheet="raw_data")
groupSuccess = tr$suss[1:30]
InfoTrack_Attack_Lead = tr[((tr$roleA1D2 == 1)&(tr$leadL1F2==1)),
                                   c("detaC_within_Tmean","detaC_within_TG","detaC_between_TG")]
InfoTrack_Attack_Follow = tr[((tr$roleA1D2 == 1)&(tr$leadL1F2==0)),
                                   c("detaC_within_Tmean","detaC_within_TG","detaC_between_TG")]
InfoTrack_Defend_Lead = tr[((tr$roleA1D2 == 2)&(tr$leadL1F2==1)),
                                   c("detaC_within_Tmean","detaC_within_TG","detaC_between_TG")]
InfoTrack_Defend_Follow = tr[((tr$roleA1D2 == 2)&(tr$leadL1F2==0)),
                                   c("detaC_within_Tmean","detaC_within_TG","detaC_between_TG")]

names(InfoTrack_Attack_Lead) = c("AL_detaC_within_Tmean","AL_detaC_within_TG","AL_detaC_between_TG")
names(InfoTrack_Attack_Follow) = c("AF_detaC_within_Tmean","AF_detaC_within_TG","AF_detaC_between_TG")
names(InfoTrack_Defend_Lead) = c("DL_detaC_within_Tmean","DL_detaC_within_TG","DL_detaC_between_TG")
names(InfoTrack_Defend_Follow) = c("DF_detaC_within_Tmean","DF_detaC_within_TG","DF_detaC_between_TG")

df_org_infoTrack = cbind(groupSuccess,InfoTrack_Attack_Lead,InfoTrack_Attack_Follow,InfoTrack_Defend_Lead,InfoTrack_Defend_Follow)
df_org_infoTrack_Attack = cbind(groupSuccess,InfoTrack_Attack_Lead,InfoTrack_Attack_Follow)
df_org_infoTrack_Defend = cbind(groupSuccess,InfoTrack_Defend_Lead,InfoTrack_Defend_Follow)
```

## Regression
```{r Regress_analysis}
model_list <- list(
model_all <- lm(groupSuccess ~ ., data = df_org_infoTrack),
model_attack <- lm(groupSuccess ~ ., data = df_org_infoTrack_Attack),
model_defend <- lm(groupSuccess ~ ., data = df_org_infoTrack_Defend)
)

R2 <- data.frame(
  Model_Name = c("model_all","model_attack","model_defend"),
  R_squared = numeric(length(model_list)),
  stringsAsFactors = FALSE
)

for (i in seq_along(model_list)) {
  model_summary <- summary(model_list[[i]])
  R2$R_squared[i] <- model_summary$r.squared
}

print(R2)
```

## Regression cross-validation
```{r cross_valid}
cv_list <- list(
cv_all = lm_cv_correlation(df_org_infoTrack,5,100,'r_value'),
cv_attack = lm_cv_correlation(df_org_infoTrack_Attack,5,100,'r_value'),
cv_defend = lm_cv_correlation(df_org_infoTrack_Defend,5,100,'r_value')
)

Rvalue <- data.frame(
  r_values = sapply(cv_list, function(x) x),
  stringsAsFactors = FALSE
)

print(Rvalue)
```

## Permutation cross-validation
```{r permutation, eval=FALSE}
#Attacker-leader
perm_all = lm_perm(df_org_infoTrack,5,5000,'r_value')
perm_attack = lm_perm(df_org_infoTrack_Attack,5,5000,'r_value')
perm_defend = lm_perm(df_org_infoTrack_Defend,5,5000,'r_value')
```

### Permutation save
```{r perm_save, eval=FALSE}
saveRDS(perm_all, "lm_perm_all_5000_r.RData")
saveRDS(perm_attack, "lm_perm_attack_5000_r.RData")
saveRDS(perm_defend, "lm_perm_defend_5000_r.RData")
```

### Permutation read
```{r perm_read}
perm_all = readRDS("lm_perm_all_5000_r.RData")
perm_attack = readRDS("lm_perm_attack_5000_r.RData")
perm_defend = readRDS("lm_perm_defend_5000_r.RData")
```

### Permutation p value
```{r Summary_R2}
p_perm_list <- list(
  p_perm_all = mean(cv_list$cv_all<perm_all$lm_perm),
  p_perm_attack = mean(cv_list$cv_attack<perm_attack$lm_perm),
  p_perm_defend = mean(cv_list$cv_defend<perm_defend$lm_perm)
)

p_perm <- data.frame(
  p_values = sapply(p_perm_list, function(x) x),
  stringsAsFactors = FALSE
)

print(p_perm)
```

## Figure
```{r linear}
mr = data.frame(df_org_infoTrack$groupSuccess, model_all$fitted.values)
names(mr) = c("measuredSuccess", "predictedSuccess")

p <- ggplot(mr, aes(x=measuredSuccess, y=predictedSuccess)) +
  geom_point(color="#0D0D0D", size = 4, alpha = 0.8) +
  geom_smooth(method=lm , color="black", se=TRUE) +
  theme_classic()
print(p)
```