---
title: "S02_Hyperparameter_tuning"
author: "Xiaochun Han"
date: "2025-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix", "glmnet", "LiblineaR","psych","ggplot2","reshape2","car"))
basedir = '/Users/xiaochunhan/Documents/Research/Projects/Brains_aligned_to_win/Supplement_analysis/S02_Hyperparameter_tuning'
```

## Import data
```{r impart data}
setwd('../../Data/Develop')
wd<-getwd()
dataset_BOLD <- read.csv('BOLD_single_trial_invest.csv',header=TRUE,sep=",")
dataset_FC <- read.csv('FC_single_trial_invest.csv',header=TRUE,sep=",")
dataset_BINS <- read.csv('BINS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('INS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

BOLD_mean = extract_win_or_pay_mean(dataset_BOLD,dataset_y_attack,"BOLD_","win",FALSE)
FC_mean = extract_win_or_pay_mean(dataset_FC,dataset_y_attack,"FC_","win",FALSE)
INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win",FALSE)
data_all_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)],BOLD_mean[,3:ncol(BOLD_mean)],FC_mean[,3:ncol(FC_mean)])
data_INS_BINS_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)])
data_BOLD_FC_invest = cbind(BOLD_mean[,c(1,3:ncol(BOLD_mean))],FC_mean[,3:ncol(FC_mean)])
```

## SVM-RBF
### All features
```{r svm_rbf_all}
params <- list(
  C_range = seq(-5, 15, length.out = 10),
  gamma_range = seq(-15, 3, length.out = 10)
)

result <- tune_sensitive(data_all_invest, params, nfold = 5)

draw_accuracy_heatmap(result$accuracy_matrix, params$C_range, params$gamma_range, 'svm_parameter_tuning_heatmap_full-model.png')

data_reorg = prepare_anova_data(result)
perform_tuning_anova(data_reorg)
```

### BOLD and FC
```{r svm_rbf_intra}
result2 <- tune_sensitive(data_BOLD_FC_invest, params, nfold = 5)

draw_accuracy_heatmap(result2$accuracy_matrix, params$C_range, params$gamma_range, 'svm_parameter_tuning_heatmap_intra-model.png')

data_reorg2 = prepare_anova_data(result2)
perform_tuning_anova(data_reorg2)
```

### INS and BINS
```{r svm_rbf_inter}
result3 <- tune_sensitive(data_INS_BINS_invest, params, nfold = 5)

draw_accuracy_heatmap(result3$accuracy_matrix, params$C_range, params$gamma_range, 'svm_parameter_tuning_heatmap_inter-model.png')

data_reorg3 = prepare_anova_data(result3)
perform_tuning_anova(data_reorg3)
```
