---
title: "Analysis1_Prediction_oneF"
author: "Xiaochun Han"
date: "2026-01-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix"))
```

## Import data
```{r impart data}
setwd('../../Data/Develop')
wd<-getwd()
dataset_BINS <- read.csv('BINS_single_trial_invest_bothF.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('INS_single_trial_invest_bothF.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE,FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win",FALSE,FALSE)
data_INS_BINS_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)])
```

## Predicting win vs. lose

### INS and BINS
#### 5-fold
```{r svm_invest_INS&BINS-5}
acc_ins_bins = svm_cv_accuracy(data_INS_BINS_invest,5,100,"radial")
print(acc_ins_bins)
```

## AUC win vs. lose

### INS and BINS
```{r auc_invest_INS&BINS}
auc_ins_bins = auc_boot_cv(data_INS_BINS_invest,5,"radial",1000,TRUE,'#AD91C4','data_INS_BINS_invest_roc_plot_bothF.png')
```

## Permutation test
```{r permute_test-5, eval=FALSE}
acc_ins_bins_perm = svm_perm(data_INS_BINS_invest,5,5000,"radial")
saveRDS(acc_ins_bins_perm, "SVM_win_INS_BINS_perm_5000_bothF.RData")
```

### Permutation read
```{r perm_read_succ}
acc_ins_bins_perm = readRDS("SVM_win_INS_BINS_perm_5000_oneF.RData")
colnames(acc_ins_bins_perm) = 'acc_perm'
```

### Permutation p value
```{r Summary_R2_succ}
p_perm_inter = mean(acc_ins_bins<acc_ins_bins_perm$acc_perm)
print(p_perm_inter)
```
